import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Razafindratsimba Bruno Ismael",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      {/* Ajouter la balise <link> dans le <head> */}
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Rigtheous:wght@600"
          rel="stylesheet"
        />
      </head>
      <body className="font-poppins">{children}</body>
    </html>
  );
}
